global:
  name: consul
  metrics:
    enabled: true
  image: hashicorp/consul:1.13.1
  imageEnvoy: envoyproxy/envoy:v1.20.2
server:
  # replicas sets the number of servers.
  # In production, this should be 3 or 5, however
  # for testing, this should be set to 1.
  replicas: 1
connectInject:
  enabled: true
controller:
  enabled: true
prometheus:
  enabled: true
ui:
  service:
    type: ClusterIP
    port:
      http: 8500
ingressGateways:
  enabled: true
  gateways:
    - name: nginx-ingress
      service:
        type: LoadBalancer