apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    app: express-portfolio-assignment
spec:
  selector:
    matchLabels:
      app: express-portfolio-assignment
      tier: reverse-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: express-portfolio-assignment
        tier: reverse-proxy
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
          name: reverse-proxy
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: nginx-config
          configMap:
            name: confnginx